# TASK LEVEL Variables

- name: Variables from PLAY LEVEL
  hosts: localhost

  #Declaring Variables
  vars:
    Course: "Devops"
    Trainer: "Sivakumar"
    Duration: "120 HOURS"
  # You can override the Variables.
  
  tasks:
  - name: Check Variables
    vars: # Task Level
      Course: "DevOps with AWS"
    ansible.builtin.debug:
      msg: "Hi, I am Learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
  # Task level Varibale Overrides Playlevel variables.