- name: VARIABLES- PREFERENCES from PLAYBOOK
  hosts: localhost

#Declaring Vaiables as Files to call the variables.yaml
  vars_files:   
    variables.yaml

 #Decalring PROMPT in variable to Display prompt in the Output 
  # vars_prompt:
  # - name: PERSON
  #   prompt: Please Enter your name
  #   private: false #user can see what they are entering

  # - name: WISHES
  #   prompt: Please Enter your wishes
  #   private: true  #user cannot see while entering Password

#So Variables  wherever we have options we are mentioning everywhere.Here Declaring in PLAY Level
  vars:
    PERSON: "Sivakumar from PLAY"
    WISHES: "Morning from PLAY"

#Declaring TASK level
  tasks:
    - name: Check Variables
      # vars:
      #   PERSON: "Siva from TASK"
      #   WISHES: "Morning from TASK"

      ansible.builtin.debug:
        msg: "Hello {{PERSON}}, Good {{WISHES}}"


#Output - Preference
# 1. CMD Line
# 2. TASK Level
# 3. 