- name: loops 
  hosts: localhost

  tasks:
  - name: Print Person
    ansible.builtin.debug:
      msg: "Hello {{item}}" # To refer the List of Values we use : item which is Default Keyword
    loop:
    - Ramesh #List of Values we can loop it.
    - Suresh
    - Ganesh