- name: ADVANCED LOOPS
  hosts: localhost
  become: yes

  tasks:
  - name: INSTALL or UNINSTALL PACKAGES
    ansible.builtin.package:
      name: "{{item.name}}"     #To refer the List of values
      state: "{{item.state}}"
    
    loop:
    - { name: 'git' , state: 'absent' }   #this entry is an  ITEM-which have multiple things. You can add as many.
    - { name: 'nginx' , state: 'present' }
    - { name: 'mysql' , state: 'present' }