- name: ping playbook
  hosts: web    # we need to mention to which Server we are connecting.It will refer to inventory file.
  tasks:        # here we are giving List of tasks.
  - name: Ping the Server
    ansible.builtin.ping: #Built in ping module. Once you RUN, it will ping the Web component.