- name: ping playbook
  hosts: web
  tasks:
  - name: ping the server
    ansible.builtin.ping:
# We are giving UN and PASS in ansible.cfg under VAULT --> which is High Secure comapre it to Ansible folder.
# In Vault, we are creating like a vault i.e.  group_vars --> we can give all our variables.